
package poo.campo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import poo.campo.dao.campodao;
import poo.campo.dao.cultivodao;
import poo.campo.dao.cultivolaboreodao;
import poo.campo.dao.estadoproyectodao;
import poo.campo.dao.laboreodao;
import poo.campo.dao.lotedao;
import poo.campo.dao.proyectodao;
import poo.campo.dao.proyectolaboreodao;
import poo.campo.ui.Campo;
import poo.campo.ui.Cultivo;
import poo.campo.ui.Cultivolaboreo;
import poo.campo.ui.Estadoproyecto;
import poo.campo.ui.Lote;
import poo.campo.ui.Proyecto;
import poo.campo.ui.Proyectolaboreo;
import java.util.Date;
import poo.campo.dao.fechadao;
import poo.campo.ui.Laboreo;

/**
 *
 * @author Normal
 */
public class JFProyectoLote extends javax.swing.JFrame {
    public Date fechaPublica;
    JTable miTabla1;
    DateFormat fechalabor= DateFormat.getDateInstance(WIDTH, Locale.ITALY);
    private ArrayList<Proyectolaboreo> arrProylab;
    /**
     * Creates new form JFProyectoLote
     */
    public JFProyectoLote() {
        initComponents();
        
        Campo c = new Campo();
        c.mostrarCampos(jComboBox1);
        
        cargarEstadosProyecto(0);     
       
        fechaPublica=new Date();
        jTextField5.setVisible(false);
        jTextField5.setText("0");
        // Accion a realizar cuando el JComboBox cambia de item seleccionado.
	jComboBox1.addActionListener(new ActionListener() {
	@Override
	public void actionPerformed(ActionEvent e) {
		cargarLotes(0);             
  
	}
	});
        jComboBox2.addActionListener(new ActionListener() {
	@Override
	public void actionPerformed(ActionEvent e) {
		 cargarCultivos(0);
	}
	});
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jDatelabor = new com.toedter.calendar.JDateChooser();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateini = new com.toedter.calendar.JDateChooser();
        jDatefin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(0, 153, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CARGAR PROYECTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Seleccionar Campo");

        jLabel2.setText("Seleccionar Lote ");

        jLabel3.setText("Fecha inicio:");

        jLabel5.setText("Fecha fin:");

        jLabel6.setText("Responsable:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCulLabor", "idCultivo", "idLaboreo", "Labor", "Orden", "Fecha", "Realizado"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(10);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(10);
            jTable1.getColumnModel().getColumn(1).setMinWidth(10);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(10);
            jTable1.getColumnModel().getColumn(2).setMinWidth(10);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(10);
        }

        jCheckBox1.setText("Realizado");

        jLabel8.setText("Fecha labor");

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Seleccione otro labor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jDatelabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jDatelabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel7.setText("Seleccionar Cultivo");

        jButton1.setText("Cargar Laboreos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GUARDAR PROYECTO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Seleccionar Estado Proyecto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateini, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, 245, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox4, 0, 245, Short.MAX_VALUE)
                                    .addComponent(jTextField3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDatefin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void cargarEstadosProyecto(int busca){              
        Estadoproyecto ep = new Estadoproyecto();
        ep.mostrarEstadoproyecto(jComboBox4);
    }
       public void cargarLaboreosNoasignados(int busca){
        
        int idcultivo;                
        idcultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        if (idcultivo>0){
              Laboreo la = new Laboreo();
              la.LaboreosnoasignadosAlcultivo(jComboBox5, idcultivo);
        }else JOptionPane.showMessageDialog(null, "NO HAY CULTIVOS SELECCIONADOS!");
    }
      public void cargarCultivos(int busca){          
        int id,idtiposuelo;  
        id=jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getIdlote();
        idtiposuelo=lotedao.BuscarTiposuelo(id);        
        Cultivo c = new Cultivo();
        c.mostrarCultivos(jComboBox3,idtiposuelo);

    }
      
      public void cargarLotes(int busca){
        int index = 1;
        int id;    
        id=jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).getIdcampo();
        Lote l = new Lote();
        l.mostrarLotes(jComboBox2,id);
    }
      
    public void construirTabla() {
       int numRows = jTable1.getSelectedRows().length;
       DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();  
       for(int i=0; i<numRows ; i++ ) { 
           modelo.removeRow(jTable1.getSelectedRow()); 
       }
       String titulos[]={ "idCultivolaboreo", "idcultivo", "idlaboreo", "Labor","Orden", "Fecha","Realizado" };
       String informacion[][]=obtenerMatriz();   
       miTabla1=new JTable(informacion,titulos); 
    }
    public String[][] obtenerMatriz() {
        Integer idCultivo;
        //borrarFilas();
        idCultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        
        laboreodao milaboreoDao=new laboreodao();
        
        ArrayList<Cultivolaboreo>miLista=cultivolaboreodao.buscarLaboreosSegunCultivoMatriz(idCultivo);
        String matrizInfo[][]=new String[miLista.size()][7];
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();  
         
        for (int i = 0; i < miLista.size(); i++) {
         matrizInfo[i][0]=miLista.get(i).getIdcultivolaboreo()+"";
         matrizInfo[i][1]=miLista.get(i).getIdcultivo()+"";
         matrizInfo[i][2]=miLista.get(i).getIdLaboreo()+"";
         matrizInfo[i][3]=miLista.get(i).getDescLaboreo()+"";
         matrizInfo[i][4]=miLista.get(i).getOrden()+"";
         matrizInfo[i][5]="";
         matrizInfo[i][6]="0";
        // System.out.println(miLista.get(i).getIdcultivo());   
         modelo.addRow(matrizInfo[i]);
        }
        jTable1.setModel(modelo);
      return matrizInfo;
 }
    public void borrarFilas(){
       TableModel m = jTable1.getModel();
       for (int f = 0; f < m.getRowCount(); f++)
       {
         for(int c = 0; c < m.getColumnCount(); c++)
         {
           m.removeTableModelListener(jTable1);
         }
       }
    }
    
    private boolean ValidarCampos() {
        boolean valida=true;
        int camposeleccionado=0;
        int loteseleccionado=0;
        int cultivoseleccionado=0;
        int estadoseleccionado=0;
        camposeleccionado=jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).getIdcampo();
        loteseleccionado=jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getIdlote();
        cultivoseleccionado=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        estadoseleccionado=jComboBox4.getItemAt(jComboBox4.getSelectedIndex()).getIdestadoproyecto();
        if(camposeleccionado==0){JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR EL CAMPO");
           valida=false;}
        if(loteseleccionado==0){JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR EL LOTE");
           valida=false;   }     
        if(cultivoseleccionado==0){JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR EL CULTIVO");
           valida=false;}
        if(estadoseleccionado==0){JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN ESTADO");
           valida=false;}
        if (jTextField3.getText()==""){JOptionPane.showMessageDialog(null, "Debe completar Responsable de");
         valida=false;}
        return valida;
    }
   
    private void CargarLaboreosdeMatriz(Integer idproyecto){
        TableModel tabla = jTable1.getModel();
        Integer idLabcul,id=0;       
        Integer idCultivo;
        idCultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MMM-yyyy"); 
        for (int i = 0; i < tabla.getRowCount(); i++) {
            
            Proyectolaboreo prolab = new Proyectolaboreo();//idproyecto,idlaboreo,fecha,nota,idlaboreocultivo,activo
            prolab.setidproyecto(idproyecto);
            id =Integer.valueOf((String) tabla.getValueAt(i,3)); 
            prolab.setidLaboreo((int)id);  
            
            String sfecha=((String) tabla.getValueAt(i,5));
            Date fe=fechadao.ConvertirStringaDate(sfecha);           
            long a =fe.getTime();
            java.sql.Date sqlfecha=new java.sql.Date(a);            
            prolab.setFecha(sqlfecha);        
            idLabcul=Integer.valueOf((String) tabla.getValueAt(i,1)); 
            prolab.setIdlaboreocultivo((int)idLabcul);
            prolab.setidCultivo((int)idCultivo);            
            prolab.setNota("");
            prolab.setActivo(true);                   
            String resp = proyectolaboreodao.registrarProyectoLaboreo(prolab);           

        }     
        
    }        
    
    private void guardar() throws ParseException{
       Integer idLote,idCultivo,idEstadoProyecto,idproyecto;
       String respo;
       Date fe;
       java.sql.Date dfechai,dfechaf;
       idproyecto=0;
       idLote=jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getIdlote();
       idCultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
       idEstadoProyecto=jComboBox4.getItemAt(jComboBox4.getSelectedIndex()).getIdestadoproyecto();
       Proyecto pro=new Proyecto();  //idproyecto,idlote,feinicio,fefin,idestadoproyecto,responsable,activo,idcultivo
       pro.setidEstadoproyecto(idEstadoProyecto);
       pro.setidcultivo(idCultivo);
       pro.setidlote(idLote);
       fe=(Date)jDateini.getDate();
       long a=fe.getTime();
       dfechai=new java.sql.Date(a);
       pro.setFeinicio(dfechai);
       fe=(Date)jDatefin.getDate();
       long b=fe.getTime();
       dfechaf=new java.sql.Date(b);
       pro.setFefin(dfechaf);
       respo=jTextField3.getText();
       pro.setResponsable(respo);
       pro.setActivo(true);     
       if (idproyecto<=0 ) idproyecto = proyectodao.registrarProyecto(pro);
       if (idproyecto>0) CargarLaboreosdeMatriz(idproyecto);  

    }
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged
//CARGAR LABORES SEGUN CULTIVO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idcultivo;
        idcultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        
        if (idcultivo>0){
            construirTabla();
            cargarLaboreosNoasignados(idcultivo);
        }else JOptionPane.showMessageDialog(null,"Debe seleccionar el Cultivo" );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int filaseleccionada;
        int val;
        String sfecha;
        Integer idcultivolaboreo=0;
        boolean boo;
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MMM-yyyy");   
        jDatelabor.setDate(fechaPublica);
            //Guardamos en un entero la fila seleccionada.
            filaseleccionada = jTable1.getSelectedRow();
            if (filaseleccionada == -1){
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
            } else {    
                jTextField5.setText(String.valueOf(filaseleccionada));
                idcultivolaboreo = Integer.parseInt((jTable1.getValueAt(filaseleccionada,1).toString()));               
                if (idcultivolaboreo>0)jComboBox5.setSelectedIndex(idcultivolaboreo);
                val= Integer.parseInt((jTable1.getValueAt(filaseleccionada,6).toString()));    
                if (val==1)boo=true; else boo=false; 
                jCheckBox1.setSelected(boo);  
                
                sfecha=(String)jTable1.getValueAt(filaseleccionada, 5); 
                if (sfecha!=""){
                    Date fe = fechadao.ConvertirStringaDate(sfecha);
                    jDatelabor.setDate(fe);
                }
                

                
            }  
      
            
            
    }//GEN-LAST:event_jTable1MouseClicked
    //ACTUALIZAR LABOR EN TABLA
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sfecha,sfila;   
        Integer asigno,idcultivo,idlaboreo,idcultivolaboreo=0;
        boolean val;
        Integer filaseleccionada =0;
        sfila=jTextField5.getText();
        sfecha="";
        if (sfila != "") {filaseleccionada =  Integer.valueOf(sfila); }          
   
        idcultivo=jComboBox3.getItemAt(jComboBox3.getSelectedIndex()).getIdcultivo();
        //edito el labor en la tabla
        if (filaseleccionada>0){             
            idlaboreo=jComboBox5.getItemAt(jComboBox5.getSelectedIndex()).getIdlaboreo(); 
            if (idlaboreo>0){
                  idcultivolaboreo=cultivolaboreodao.getidCultivolaboreo(idlaboreo, idcultivo);   
            }
            val= jCheckBox1.isSelected();            
            if (val==true)asigno=1;else asigno=0;
            
            if ("".equals( this.jDatelabor.getDate())) sfecha="";  
                else{
                    Date fecha=(jDatelabor.getDate());
                    if (fecha == null )sfecha=""; 
                    else {
                    DateFormat f=new SimpleDateFormat("dd-MM-yyyy");
                    sfecha=f.format(fecha); }
                }          
            jTable1.setValueAt(idcultivolaboreo, filaseleccionada, 1);    
            jTable1.setValueAt(sfecha, filaseleccionada, 5);
            jTable1.setValueAt(asigno, filaseleccionada, 6);                    
        } 
        else // nuevo labore
        {
            idlaboreo=jComboBox5.getItemAt(jComboBox5.getSelectedIndex()).getIdlaboreo(); 
            
            if (idlaboreo>0){
                idcultivolaboreo=cultivolaboreodao.getidCultivolaboreo(idlaboreo, idcultivo);                      
                val= jCheckBox1.isSelected();            
                if (val==true)asigno=1; else asigno=0;             
                
                if ("".equals( this.jDatelabor.getDate())) sfecha="";  
                else{
                    Date fecha=(jDatelabor.getDate());
                    if (fecha == null )sfecha=""; 
                    else {
                    DateFormat f=new SimpleDateFormat("dd-MM-yyyy");
                    sfecha=f.format(fecha); }
                }        
            
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                  String idcullab= String.valueOf(idcultivolaboreo);    
                  String idcul= String.valueOf(idcultivo); 
                  String idlab=  String.valueOf(idlaboreo); 
                  String labor= (String) jComboBox5.getSelectedItem();
                  String orden= "";
                  String fe=sfecha ;
                  String realizado=  String.valueOf(asigno); 
                  String[] datos = {idcullab,idcul,idlab, labor, orden,fe,realizado};                                
                  modelo.addRow(datos);                    
                  this.jTable1.setModel(modelo); 
            }else JOptionPane.showMessageDialog(null, "Debe seleccionar un nuevo labor");
             
        }
        jTextField5.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed
//GUARDAR PROYECTO 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       boolean valida;
       valida=ValidarCampos();     
       if (valida==true){
           try {
               guardar();
           } catch (ParseException ex) {
               Logger.getLogger(JFProyectoLote.class.getName()).log(Level.SEVERE, null, ex);
           }
         
        }
         
    }//GEN-LAST:event_jButton4ActionPerformed
//CANCELAR PROYECTO 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         System.exit(0);  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProyectoLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProyectoLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProyectoLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProyectoLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProyectoLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<Campo> jComboBox1;
    private javax.swing.JComboBox<Lote> jComboBox2;
    private javax.swing.JComboBox<Cultivo> jComboBox3;
    private javax.swing.JComboBox<Estadoproyecto> jComboBox4;
    private javax.swing.JComboBox<Laboreo> jComboBox5;
    private com.toedter.calendar.JDateChooser jDatefin;
    private com.toedter.calendar.JDateChooser jDateini;
    private com.toedter.calendar.JDateChooser jDatelabor;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private Date ConvertirStringaDate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
