package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Campo generated by hbm2java
 */
public class Campo  implements java.io.Serializable {


     private Integer idcampo;
     private Estadocampo estadocampo;
     private String descripcion;
     private int superficie;
     private boolean activo;
     private Set lotes = new HashSet(0);
     private String resultado;
     private int idestadocampo;

    public Campo() {
    }

	
    public Campo(Estadocampo estadocampo, String descripcion, int superficie, boolean activo) {
        this.estadocampo = estadocampo;
        this.descripcion = descripcion;
        this.superficie = superficie;
        this.activo = activo;
    }
    public Campo(Estadocampo estadocampo, String descripcion, int superficie, boolean activo, Set lotes) {
       this.estadocampo = estadocampo;
       this.descripcion = descripcion;
       this.superficie = superficie;
       this.activo = activo;
       this.lotes = lotes;
    }
    public Campo( int id, String descripcion) {
       this.idcampo=id;
       this.descripcion = descripcion;
       
    }
   
    public String getResultado() {
        return resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    public Integer getIdcampo() {
        return this.idcampo;
    }

    public void setIdcampo(Integer idcampo) {
        this.idcampo = idcampo;
    }
    
    public Integer getidestadocampo() {
        return this.idestadocampo;
    }   
    
    public void setidestadocampo(Integer idestadocampo) {
        this.idestadocampo = idestadocampo;
    }  
    
    public Estadocampo getEstadocampo() {
        return this.estadocampo;
    }
    
    public void setEstadocampo(Estadocampo estadocampo) {
        this.estadocampo = estadocampo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(int superficie) {
        this.superficie = superficie;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }

    public void mostrarCampos(JComboBox<Campo> comboCampo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Campo c = null;
        String sql = "SELECT * FROM campo";
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboCampo.addItem(
                     new Campo( 
                        rs.getInt("idcampo"),
                        rs.getString("descripcion")
                     
                        )
                   );
            }   

        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}
    public String toString (){
        return descripcion;
    }

}


