package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Cultivo generated by hbm2java
 */
public class Cultivo  implements java.io.Serializable {


     private Integer idcultivo;
     private String descripcion;
     private boolean activo;
     private Set tiposuelocultivos = new HashSet(0);
     private Set cultivolaboreos = new HashSet(0);

    public Cultivo() {
    }

	
    public Cultivo(int idcultivo, String descripcion) {
        this.idcultivo=idcultivo;
        this.descripcion = descripcion;
    }
    public Cultivo(String descripcion, boolean activo, Set tiposuelocultivos, Set cultivolaboreos) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.tiposuelocultivos = tiposuelocultivos;
       this.cultivolaboreos = cultivolaboreos;
    }
   
    public Integer getIdcultivo() {
        return this.idcultivo;
    }
    
    public void setIdcultivo(Integer idcultivo) {
        this.idcultivo = idcultivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTiposuelocultivos() {
        return this.tiposuelocultivos;
    }
    
    public void setTiposuelocultivos(Set tiposuelocultivos) {
        this.tiposuelocultivos = tiposuelocultivos;
    }
    public Set getCultivolaboreos() {
        return this.cultivolaboreos;
    }
    
    public void setCultivolaboreos(Set cultivolaboreos) {
        this.cultivolaboreos = cultivolaboreos;
    }

    public String toString (){
        return descripcion;
    }

    public void mostrarCultivos(JComboBox<Cultivo> comboCultivos,int idtiposuelo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Cultivo c = null;
        String sql = "SELECT cultivo.idcultivo,cultivo.descripcion FROM tiposuelocultivo\n" +
        "left join cultivo \n" +
        "on tiposuelocultivo.idcultivo= cultivo.idcultivo\n" +
        "where idtiposuelo=" + idtiposuelo;
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboCultivos.addItem(
                     new Cultivo( 
                        rs.getInt("idcultivo"),
                        rs.getString("descripcion")                    
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}



}


