package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1






/**
 * Cultivolaboreo generated by hbm2java
 */
public class Cultivolaboreo  implements java.io.Serializable {


     private Integer idcultivolaboreo;
     private Cultivo cultivo;
     private Laboreo laboreo;
     private Integer orden;
     private boolean activo;
     private Integer idcultivo;
     private Integer idlaboreo;
     private String desclaboreo;
    public Cultivolaboreo() {
    }

	
    public Cultivolaboreo(Cultivo cultivo, Laboreo laboreo, boolean activo) {
        this.cultivo = cultivo;
        this.laboreo = laboreo;
        this.activo = activo;
    }
    public Cultivolaboreo(Cultivo cultivo, Laboreo laboreo, Integer orden, boolean activo) {
       this.cultivo = cultivo;
       this.laboreo = laboreo;
       this.orden = orden;
       this.activo = activo;
    }
    public Cultivolaboreo(Cultivo cultivo, Laboreo laboreo, Integer orden, boolean activo, Integer idcultivo, Integer idlaboreo, String descr) {
       this.cultivo = cultivo;
       this.laboreo = laboreo;
       this.orden = orden;
       this.activo = activo;
       this.idlaboreo=idlaboreo;
       this.idcultivo=idcultivo;
       this.desclaboreo=descr;
    }
    public Integer getIdcultivolaboreo() {
        return this.idcultivolaboreo;
    }
    
    public void setIdcultivolaboreo(Integer idcultivolaboreo) {
        this.idcultivolaboreo = idcultivolaboreo;
    }
    public Cultivo getCultivo() {
        return this.cultivo;
    }   
    public String getDescLaboreo() {
        return desclaboreo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }
    public Laboreo getLaboreo() {
        return this.laboreo;
    }
    public Integer getIdcultivo() {
        return this.idcultivo;
    }
    public Integer getIdLaboreo() {
        return this.idlaboreo;
    }
    public void setLaboreo(Laboreo laboreo) {
        this.laboreo = laboreo;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public void setidCultivo(Integer idCultivo) {
        this.idcultivo = idCultivo;
    }
    public void setidLaboreo(Integer idlaboreo) {
        this.idlaboreo = idlaboreo;
    }
    public void setDescLaboreo(String desclab) {
        this.desclaboreo = desclab;
    }


}


