package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Estadocampo generated by hbm2java
 */
public class Estadocampo  implements java.io.Serializable {


     private Integer idestadoCampo;
     private String descripcion;
     private boolean activo;
     private Set campos = new HashSet(0);

    public Estadocampo() {
    }

	
    public Estadocampo(int id,String descripcion) {
        this.idestadoCampo=id;
        this.descripcion = descripcion;
    }
    public Estadocampo(String descripcion, boolean activo, Set campos) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.campos = campos;
    }
    public Estadocampo(String descripcion, boolean activo) {
       this.descripcion = descripcion;
       this.activo = activo;
    }
   
    public Integer getIdestadoCampo() {
        return this.idestadoCampo;
    }
    
    public void setIdestadoCampo(Integer idestadoCampo) {
        this.idestadoCampo = idestadoCampo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getCampos() {
        return this.campos;
    }
    
    public void setCampos(Set campos) {
        this.campos = campos;
    }



    public void mostrarEstadoCampo(JComboBox<Estadocampo> comboEstadocampo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Estadocampo ec = null;
        String sql = "SELECT * FROM estadocampo";
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboEstadocampo.addItem(
                     new Estadocampo( 
                        rs.getInt("idestadocampo"),
                        rs.getString("descripcion")                     
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}
    public String toString (){
        return descripcion;
    }



}


