package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Estadoproyecto generated by hbm2java
 */
public class Estadoproyecto  implements java.io.Serializable {


     private Integer idestadoproyecto;
     private String descripcion;
     private boolean activo;
     private Set proyectos = new HashSet(0);

    public Estadoproyecto() {
    }

	
    public Estadoproyecto(int id, String descripcion) {
        this.idestadoproyecto=id;
        this.descripcion = descripcion;
    }
    public Estadoproyecto(String descripcion, boolean activo, Set proyectos) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.proyectos = proyectos;
    }
   
    public Integer getIdestadoproyecto() {
        return this.idestadoproyecto;
    }
    
    public void setIdestadoproyecto(Integer idestadoproyecto) {
        this.idestadoproyecto = idestadoproyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    public void mostrarEstadoproyecto(JComboBox<Estadoproyecto> comboEstadoproyecto){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Estadoproyecto ep = null;
        String sql = "SELECT * FROM estadoproyecto";
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboEstadoproyecto.addItem(
                     new Estadoproyecto( 
                        rs.getInt("idestadoproyecto"),
                        rs.getString("descripcion")
                     
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}
    public String toString (){
        return descripcion;
    }



}


