package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Laboreo generated by hbm2java
 */
public class Laboreo  implements java.io.Serializable {


     private Integer idlaboreo;
     private String descripcion;
     private boolean activo;
     private Set proyectolaboreos = new HashSet(0);
     private Set cultivolaboreos = new HashSet(0);

    public Laboreo() {
    }

	
    public Laboreo(int idlaboreo, String descripcion) {
        this.idlaboreo=idlaboreo;
        this.descripcion = descripcion;
        
    }
    public Laboreo(String descripcion, boolean activo, Set proyectolaboreos, Set cultivolaboreos) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.proyectolaboreos = proyectolaboreos;
       this.cultivolaboreos = cultivolaboreos;
    }
   
    public Integer getIdlaboreo() {
        return this.idlaboreo;
    }
    
    public void setIdlaboreo(Integer idlaboreo) {
        this.idlaboreo = idlaboreo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getProyectolaboreos() {
        return this.proyectolaboreos;
    }
    
    public void setProyectolaboreos(Set proyectolaboreos) {
        this.proyectolaboreos = proyectolaboreos;
    }
    public Set getCultivolaboreos() {
        return this.cultivolaboreos;
    }
    
    public void setCultivolaboreos(Set cultivolaboreos) {
        this.cultivolaboreos = cultivolaboreos;
    }

    public String toString (){
        return descripcion;
    }

    
   

    public void LaboreosnoasignadosAlcultivo(JComboBox<Laboreo> comboLaboreo,int idcultivo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Laboreo la = null;
        String sql = "select  laboreo.idlaboreo,laboreo.descripcion, (select IFNULL(cultivolaboreo.idcultivolaboreo,0))\n" +
        "from laboreo\n" +
        "left join cultivolaboreo on laboreo.idlaboreo = cultivolaboreo.idlaboreo\n" +
        "left join cultivo on cultivolaboreo.idcultivo= cultivo.idcultivo\n" +
        "where  (cultivolaboreo.idcultivo=" + idcultivo + " or cultivolaboreo.idcultivo is null) and  laboreo.activo=1" ;
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboLaboreo.addItem(
                     new Laboreo( 
                        rs.getInt("idlaboreo"),
                        rs.getString("descripcion")                    
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}


}


