package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private Integer idlote;
     private Campo campo;
     private Tiposuelo tiposuelo;
     private int numero;
     private String descripcion;
     private int superficie;
     private int idTiposuelo;
     private Integer idCampo;
     private Set proyectos = new HashSet(0);

    public Lote() {
    }

	
    public Lote(Campo campo, Tiposuelo tiposuelo, int numero, String descripcion, int superficie) {
        this.campo = campo;
        this.tiposuelo = tiposuelo;
        this.numero = numero;
        this.descripcion = descripcion;
        this.superficie = superficie;
    }
    public Lote(Campo campo, Tiposuelo tiposuelo, int numero, String descripcion, int superficie, Set proyectos) {
       this.campo = campo;
       this.tiposuelo = tiposuelo;
       this.numero = numero;
       this.descripcion = descripcion;
       this.superficie = superficie;
       this.proyectos = proyectos;
    }
    public Lote( int id, String descripcion) {
       this.idlote=id;
       this.descripcion = descripcion;
       
    }
      
    public Integer getIdlote() {
        return this.idlote;
    }
    
    public void setIdlote(Integer idlote) {
        this.idlote = idlote;
    }
    public void setidTipoSuelo(Integer idTipoSuelo) {
        this.idTiposuelo = idTipoSuelo;
    }
    public void setidCampo(Integer idCampo) {
        this.idCampo = idCampo;
    }
    public Campo getCampo() {
        return this.campo;
    }
    
    public void setCampo(Campo campo) {
        this.campo = campo;
    }
    public Tiposuelo getTiposuelo() {
        return this.tiposuelo;
    }
    
    public void setTiposuelo(Tiposuelo tiposuelo) {
        this.tiposuelo = tiposuelo;
    }
    public int getNumero() {
        return this.numero;
    }
    public int getidTipoSuelo() {
        return this.idTiposuelo;
    }
    public int getidCampo() {
        return this.idCampo;
    }
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(int superficie) {
        this.superficie = superficie;
    }
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    public String toString (){
        return descripcion;
    }

    public void mostrarLotes(JComboBox<Lote> comboLote,int idcampo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Lote l = null;
        String sql = "SELECT * FROM lote  WHERE idcampo=" + idcampo;
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboLote.addItem(
                     new Lote( 
                        rs.getInt("idlote"),
                        rs.getString("descripcion")                    
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}


}


