package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idproyecto;
     private Estadoproyecto estadoproyecto;
     private Lote lote;
     private Cultivo cultivo;
     private java.sql.Date feinicio;
     private java.sql.Date fefin;
     private String responsable;
     private boolean activo;
     private Set proyectolaboreos = new HashSet(0);

     private Integer idlote;
     private Integer idestadoproyecto;
     private Integer idcultivo;
     private String fe;
     
    public Proyecto() {
    }

	
    public Proyecto(Estadoproyecto estadoproyecto, Lote lote, java.sql.Date feinicio, String responsable, boolean activo) {
        this.estadoproyecto = estadoproyecto;
        this.lote = lote;
        this.feinicio = feinicio;
        this.responsable = responsable;
        this.activo = activo;
        
    }
    public Proyecto(Estadoproyecto estadoproyecto, Lote lote, java.sql.Date feinicio, java.sql.Date fefin, String responsable, boolean activo, Set proyectolaboreos) {
       this.estadoproyecto = estadoproyecto;
       this.lote = lote;
       this.feinicio = feinicio;
       this.fefin = fefin;
       this.responsable = responsable;
       this.activo = activo;
       this.proyectolaboreos = proyectolaboreos;
    }
   
    public Integer getIdproyecto() {
        return this.idproyecto;
    }
       
    public void setIdproyecto(Integer idproyecto) {
        this.idproyecto = idproyecto;
    }
    public void setidlote(Integer idLote) {
        this.idlote = idLote;
    }
    public void setidcultivo(Integer idcultivo) {
        this.idcultivo = idcultivo;
    }
    public void setidEstadoproyecto(Integer idestadoproyecto) {
        this.idestadoproyecto = idestadoproyecto;
    }
    public Estadoproyecto getEstadoproyecto() {
        return this.estadoproyecto;
    }
    
    public void setEstadoproyecto(Estadoproyecto estadoproyecto) {
        this.estadoproyecto = estadoproyecto;
    }
    public Lote getLote() {
        return this.lote;
    }
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    public void setLote(Lote lote) {
        this.lote = lote;
    }
        
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }
    public Date getFeinicio() {
        return this.feinicio;
    }
    
    public void setFeinicio(java.sql.Date feinicio) {
        this.feinicio = feinicio;
    }
    public Date getFefin() {
        return this.fefin;
    }
    
    public void setFefin(java.sql.Date fefin) {
        this.fefin = fefin;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    public Integer getidestadoproyecto() {
        return this.idestadoproyecto;
    }
    public Integer getidlote() {
        return this.idlote;
    }
    public Integer getidcultivo() {
        return this.idcultivo;
    }        
    public Set getProyectolaboreos() {
        return this.proyectolaboreos;
    }
    
    public void setProyectolaboreos(Set proyectolaboreos) {
        this.proyectolaboreos = proyectolaboreos;
    }
    
    

    public void setfe(String fe) {
        this.fe = fe;
    }


}


