package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1



/**
 * Tiposuelocultivo generated by hbm2java
 */
public class Tiposuelocultivo  implements java.io.Serializable {


     private Integer idtiposuelocultivo;
     private Cultivo cultivo;
     private Tiposuelo tiposuelo;
     private boolean activo;

    public Tiposuelocultivo() {
    }

    public Tiposuelocultivo(Cultivo cultivo, Tiposuelo tiposuelo, boolean activo) {
       this.cultivo = cultivo;
       this.tiposuelo = tiposuelo;
       this.activo = activo;
    }
   
    public Integer getIdtiposuelocultivo() {
        return this.idtiposuelocultivo;
    }
    
    public void setIdtiposuelocultivo(Integer idtiposuelocultivo) {
        this.idtiposuelocultivo = idtiposuelocultivo;
    }
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }
    public Tiposuelo getTiposuelo() {
        return this.tiposuelo;
    }
    
    public void setTiposuelo(Tiposuelo tiposuelo) {
        this.tiposuelo = tiposuelo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


