package poo.campo.ui;
// Generated 11/12/2018 10:20:40 by Hibernate Tools 4.3.1


import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;

/**
 * Tiposuelo generated by hbm2java
 */
public class Tiposuelo  implements java.io.Serializable {


     private Integer idtiposuelo;
     private int numero;
     private String descripcion;
     private boolean activo;
     private Set lotes = new HashSet(0);
     private Set tiposuelocultivos = new HashSet(0);

    public Tiposuelo() {
    }

    public Tiposuelo(int idtiposuelo, String descripcion) {
        this.idtiposuelo = idtiposuelo;
        this.descripcion = descripcion;
    }
    public Tiposuelo(int numero, String descripcion, boolean activo) {
        this.numero = numero;
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Tiposuelo(int numero, String descripcion, boolean activo, Set lotes, Set tiposuelocultivos) {
       this.numero = numero;
       this.descripcion = descripcion;
       this.activo = activo;
       this.lotes = lotes;
       this.tiposuelocultivos = tiposuelocultivos;
    }
   
    public Integer getIdtiposuelo() {
        return this.idtiposuelo;
    }
    
    public void setIdtiposuelo(Integer idtiposuelo) {
        this.idtiposuelo = idtiposuelo;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }
    public Set getTiposuelocultivos() {
        return this.tiposuelocultivos;
    }
    
    public void setTiposuelocultivos(Set tiposuelocultivos) {
        this.tiposuelocultivos = tiposuelocultivos;
    }




    public void mostrarTiposuelo(JComboBox<Tiposuelo> comboTiposuelo){
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pst = null;
        Tiposuelo ts = null;
        String sql = "SELECT * FROM tiposuelo";
        try {
            pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                comboTiposuelo.addItem(
                     new Tiposuelo( 
                        rs.getInt("idtiposuelo"),
                        rs.getString("descripcion")                     
                        )
                   );
            }   
        } catch (SQLException e) {
            System.out.println("Error en la consulta: " + e.getMessage());
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                    cc.desconectar();
                    pst.close();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

}
    public String toString (){
        return descripcion;
    }


}


